CC=gcc
COMPILEROPTIONS = -Wall -Wextra

default:
	rm -f lab3b
	chmod u+x lab3b.sh
	ln lab3b.sh lab3b
	chmod u+x lab3b

dist:
	tar -czvf lab3b-305087992.tar.gz Makefile README lab3b.py lab3b.sh

clean:
	rm -f lab3b *.tar.gz